// <auto-generated />
namespace WebApplicationEcoleWeb.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Stagiaire3 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Stagiaire3));
        
        string IMigrationMetadata.Id
        {
            get { return "202010091215220_Stagiaire3"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
